url.productInfo=url.wcsurl+"GoodsDetailMainCmd?"+url.parms+"&jsoncallback=?";url.productType=url.wcsurl+"GoodsDetailRelatedClsCmd?"+url.parms;url.productHistory=url.wcsurl+"GoodsDetailRecentHistoryCmd?"+url.parms;url.addbag=url.wcsurl+"XOrderItemAddCmd?"+url.parms+"&random="+url.nowDate+"&jsoncallback=?";url.toFavo=url.wcsurl+"XInterestItemAddCmd?"+url.parms;url.installmentHelp="/help/201109191424.shtml";url.toShare=url.wcsurl+"shareCmd?"+url.parms;url.arrNotice=url.wcsurl+"dhNoticeCmd?"+url.parms;
var kill_param=getQueryString("kill");kill_param=="1"?$("#sellType").val("1"):$(".c_rtop").find("img").each(function(){$(this).attr("src").indexOf("230fb728-17e2-4e01-b73c-d0fab37ef860.png")>0&&$(this).remove()});$goodsInfo=$("#goodsInfoBox");var positions=$("#positionBox > a");
if(positions.length>=4){var third=positions.get(3);$goodsInfo.data("GoodsTypeId",third.href.substring(third.href.lastIndexOf("/")+1,third.href.lastIndexOf(".")))}else if(positions.length==1){third=positions.get(0);$goodsInfo.data("GoodsTypeId","")}else{third=positions.last();$goodsInfo.data("GoodsTypeId",third.attr("href").substring(third.attr("href").lastIndexOf("/")+1,third.attr("href").lastIndexOf(".")))}
$("#container_ul li").click(function(){var b=$("#container_ul li").index(this);id=$("#container"+b);b=id.find("img");for(var a=0;a<b.length;a++){var c=$(b[a]).attr("src2");if(c){$(b[a]).attr("src",c);$(b[a]).removeAttr("src2")}}id.show().siblings("div.container").hide();$(this).addClass("on").siblings("").removeClass("on")});$("#container_ul li a").click(function(){$(this).parent("li").trigger("click");this.style.outline="none";return false});$("#smallPic a").click(function(){$(this).parent("dd").siblings().removeClass("dc").end().addClass("dc")});
$("#sellType").val()=="4"&&$("#sellType").val("5");var goodsData={goodsId:$("#goodsId").val(),goodsSn:$("#goodsSn").val(),sellType:$("#sellType").val()};

function share(b){var a=$goodsInfo.data("goodInfo"),c=$("#goodsName").val(),d=window.location.href,e=skuInfo[0].pic_url+"g1_300_300.jpg?"+skuInfo[0].img_version,f=a.XPrice,h=a.MPrice;a=a.PPrice;a=url.toShare+"&goodsId="+goodsData.goodsId+"&selltype="+($("#sellType").val==""?"5":$("#sellType").val())+"&goodsSn="+goodsData.goodsSn+"&random="+url.nowDate+"&jsoncallback=?";switch(b){case 1:share_tx_wb(d,e,c,h,f);xclkFB(3);break;case 2:share_renren(d,e,c,h,f);xclkFB(3);break;case 3:share_vivi(d,e,c,h,
f);xclkFB(3);break;case 4:shareKaiXin(d,e,c,h,f);xclkFB(3);break;case 5:shareSouHu(d,e,c,h,f);xclkFB(3);break;case 6:window.open(a);xclkFB(3);break;case 7:shareMLS(d,e,c,h,f);xclkFB(3);break;default:break}}
function loadShare(){$("#shareBox").html('<span>\u5206\u4eab\u5230\uff1a</span><a href="javascript:;" onclick="share(1)" id="share1" title="\u5206\u4eab\u5230\u817e\u8baf\u5fae\u535a"></a><a href="javascript:;" onclick="share(2)" title="\u5206\u4eab\u5230\u4eba\u4eba\u7f51"></a><a href="javascript:;" onclick="share(3)" title="\u5206\u4eab\u5230\u65b0\u6d6a"></a><a href="javascript:;" onclick="share(4)" title="\u5206\u4eab\u5230\u5f00\u5fc3\u7f51"></a><a href="javascript:;" onclick="share(5)" title="\u5206\u4eab\u5230\u641c\u72d0"></a><a href="javascript:;" onclick="share(7)" title="\u5206\u4eab\u5230\u7f8e\u4e3d\u8bf4"></a><a href="javascript:;" onclick="share(6)" title="\u5206\u4eab\u5230\u90ae\u4ef6"></a>')}
function recordGoodsIds(){var b=$("#goodsId").val(),a=$("#sellType").val();b=b+"@"+a;if(!$.cookie("goodIds")||$.cookie("goodIds")=="")$.cookie("goodIds",b,{expires:7,path:"/",domain:".xiu.com"});else{a=$.cookie("goodIds").split(",");a=$.map(a,function(c){return c==b?null:c});a.length==10&&a.pop();a.unshift(b);$.cookie("goodIds",a,{expires:7,path:"/",domain:".xiu.com"})}}
function arrSingle(b){for(var a=[],c=0,d=0,e;(e=b[d++])||e===0;c=0){for(var f=0,h;(h=a[f++])||h===0;)if(e==h){c=1;break}c||a.push(e)}return a}function getParaValue(b,a){b=a.split(b);a=b.length;if(a<2)return-1;b=b[a-1].split("&")[0].replace(/=/,"");return encodeURIComponent(b)}
function abtestRecomOrBfd(){$.ajax({type:"GET",url:"http://abtest.xiu.com/GetScriptServlet.js?_pid=3",dataType:"script",timeout:2E3,complete:function(){if(typeof obj!="undefined"){var b=obj.name.indexOf("?")>-1?obj.name.substring(0,obj.name.indexOf("?")):"",a="|abproject_id=3|abitem_id=3|abverid=0";if(b!="")a="|abproject_id="+getParaValue("abproject_id",obj.name)+"|abitem_id="+getParaValue("abitem_id",obj.name)+"|abverid="+getParaValue("abverid",obj.name);b==="1"?bfd():putRecomFn();XIU.Window.ctraceClick("atype=exposuret"+
a,"recommend_engine")}else{url.nowDate%2?bfd():putRecomFn();XIU.Window.ctraceClick("atype=exposuret|abproject_id=3|abitem_id=3|abverid=0","recommend_engine")}}})}
function getType(){var b=$("#goodsId").val(),a=$("#goodsSn").val(),c=[],d=[];$.ajax({type:"POST",url:url.productType+"&goodsId="+b+"&goodsSn="+a+"&random="+url.nowDate+"&jsoncallback=?",dataType:"json",success:function(e){e=jsonData(e);if(e=="")return false;var f="";$.each(e,function(l,g){c.push(g.id+"_"+g.name);f=g.id});if($goodsInfo.data("GoodsTypeId")==""||$goodsInfo.data("GoodsTypeId").indexOf("-")!=-1)$goodsInfo.data("GoodsTypeId",f);e=arrSingle(c);for(var h=0;h<e.length;h++){var m=e[h].split("_")[1];
d.push(m)}$goodsInfo.data("type",d)},complete:function(){abtestRecomOrBfd();recomFn()}})}
function getHistory(){}
function jumpToShoppingBag(b,a){var c;if(a==null||a==""){a=$("#sellType").val();a=a.split(",");for(var d=0;d<a.length;d++)if(a[d]!="6"){c=a[d];break}}else c=a;$.cookie("shoppingLast",location.href,{path:"/",domain:".xiu.com"});location.href=url.wcsurl+"XOrderItemDisplayCmd?"+url.parms+"&wcsOrderId="+b+"&sellType="+c+"&shoppingFrom=itemAdd"}
function clearVal(b,a){if(b.value=="\u7535\u5b50\u90ae\u4ef6\uff1a"||b.value=="\u624b\u673a\u53f7\u7801\uff1a")b.value="";b.className="input";if(document.getElementById(b.id+"Tip"))document.getElementById(b.id+"Tip").innerHTML="";b.onblur=function(){if(b.value.length<1){b.value=a;b.className="input tip"}}}function valIsEmpty(b){b=b.replace(/(^\s*)|(\s*$)/g,"");if(b.length)return true;return false}
function isEmail(b){if(!/\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/.exec(b))return false;return true}function isChn(b){if(!/^[u4E00-u9FA5]+$/.test(b))return false;return true}function isPhone(b){if(!/^1[0-9]{10}$/.exec(b))return false;return true}
function countSpriceOne(b,a){var c=Math.floor(Number(new Date(b.substr(0,4),b.substr(5,2)-1,b.substr(8,2),b.substr(11,2),b.substr(14,2),b.substr(17,2)))/1E3),d=Math.floor(Number(new Date(a.substr(0,4),a.substr(5,2)-1,a.substr(8,2),a.substr(11,2),a.substr(14,2),a.substr(17,2)))/1E3);if(c-d>0)countSprice(b,a);else return false;return true}
function countSprice(b,a){try{var c=Math.floor(Number(new Date(b.substr(0,4),b.substr(5,2)-1,b.substr(8,2),b.substr(11,2),b.substr(14,2),b.substr(17,2)))/1E3),d=Math.floor(Number(new Date(a.substr(0,4),a.substr(5,2)-1,a.substr(8,2),a.substr(11,2),a.substr(14,2),a.substr(17,2)))/1E3),e=$("#onlyTimeSprice").data("diffTime")?$("#onlyTimeSprice").data("diffTime"):c-d;$("#onlyTimeSprice").data("diffTime",e-1);e=$("#onlyTimeSprice").data("diffTime");if(e<=0){$("#onlySecondSprice").text("00");$("#prd_price_div").remove();
$("#prd_attr_div").remove();$goodsInfo=$("#goodsInfoBox");$("#productLoading").show();loadProductInfo(new Date);return false}var f=Math.floor(e/86400);e%=86400;var h=Math.floor(e/3600);e%=3600;var m=Math.floor(e/60);e%=60;c=e;if(h<=9)h="0"+h;if(m<=9)m="0"+m;if(c<=9)c="0"+c;$("#onlyDaySprice").text(f);$("#onlyHourSprice").text(h);$("#onlyMinuteSprice").text(m);$("#onlySecondSprice").text(c)}catch(l){}window.setTimeout(function(){countSprice(b,a)},1E3)}
function countdown(b,a){var c=Math.floor(Number(new Date(b.substr(0,4),b.substr(5,2)-1,b.substr(8,2),b.substr(11,2),b.substr(14,2),b.substr(17,2)))/1E3),d=Math.floor(Number(new Date(a.substr(0,4),a.substr(5,2)-1,a.substr(8,2),a.substr(11,2),a.substr(14,2),a.substr(17,2)))/1E3),e=$("#onlyTime").data("diffTime")?$("#onlyTime").data("diffTime"):c-d;$("#onlyTime").data("diffTime",e-1);e=$("#onlyTime").data("diffTime");if(e<=0){$goodsInfo.data("kill",false);$("#onlyTime").text("\u5269\u4f59\u65f6\u95f4\uff1a\u79d2\u6740\u5df2\u8fc7\u671f");
return false}c=Math.floor(e/86400);e%=86400;d=Math.floor(e/3600);e%=3600;var f=Math.floor(e/60);e%=60;e=e;if(d<=9)d="0"+d;if(f<=9)f="0"+f;if(e<=9)e="0"+e;$("#onlyDay").text(c);$("#onlyHour").text(d);$("#onlyMinute").text(f);$("#onlySecond").text(e);window.setTimeout(function(){countdown(b,a)},1E3)}
function countdownPreSale(b,a){b=Math.floor(Number(new Date(b.substr(0,4),b.substr(5,2)-1,b.substr(8,2),b.substr(11,2),b.substr(14,2),b.substr(17,2)))/1E3);a=Math.floor(Number(new Date(a.substr(0,4),a.substr(5,2)-1,a.substr(8,2),a.substr(11,2),a.substr(14,2),a.substr(17,2)))/1E3);a=$("#onlyTime").data("diffTime")?$("#onlyTime").data("diffTime"):b-a;a=Math.floor(a/3600);a=Math.floor(a/24);$("#preSaleDay").text(a)}
function addToFavo(b){var a=$(b).offset();$.ajax({type:"POST",url:url.toFavo+"&catentryId="+$("#goodsId").val()+"&random="+url.nowDate+"&sellType="+$("#sellType").val()+"&jsoncallback=?",dataType:"json",success:function(c){c=jsonData(c);var d="\u52a0\u5165\u5230\u6536\u85cf\u5939\u6210\u529f";if(c.seccessfull=="N")d=c.message;xiuTips(d,a.left,a.top-46,2)},error:function(){xiuTips("\u52a0\u5165\u6536\u85cf\u5939\u5931\u8d25",a.left,a.top-46,2)}});xclkFB(1);return false}
function addShopingBag(b,a){switch(a){case 1:sendUserBuyBtnClickData("miaosha");break;case 20:sendUserBuyBtnClickData("daohuotongzhi");break;default:sendUserBuyBtnClickData("gouwudai");break}if(a!=null&(a==6||a==1))d=a;else for(var c=$("#sellType").val().split(","),d,e=0;e<c.length;e++)if(c[e]!="6"){d=c[e];break}var f=$(b).offset();e=$goodsInfo.data("cid")?$goodsInfo.data("cid"):false;var h=$goodsInfo.data("sid")?$goodsInfo.data("sid"):false;if(!e||e==-1)xiuTips("\u8bf7\u5148\u9009\u62e9 <u>"+$goodsInfo.data("colorsName")+
"</u>",f.left,f.top-43,2);else if(!h||h==-1)xiuTips("\u8bf7\u5148\u9009\u62e9 <u>"+$goodsInfo.data("sizesName")+"</u>",f.left,f.top-43,2);else{if(!checkBuyMumber($("#inputQuantity")))return false;c=$("#inputQuantity").val();if(c>1&&d==6){showTipDiv("\u5206\u671f\u4ed8\u6b3e\u53ea\u80fd\u8d2d\u4e70\u4e00\u4ef6\u5546\u54c1",f.left,f.top-44,2);return false}$("#"+e).text();$("#"+h).text();var m=$goodsInfo.data("catentryId");e=$goodsInfo.data("part_number");var l={sellType:d,part_number:e,method:"new",
catentryId:m,inputQuantity:c,goods_sn:$("#goodsSn").val()};switch(a){case 1:kill(b);break;case 6:appInstallment(b,l);xclkFB(2);break;case 20:xclkFB(4);$.xiupop({title:"\u5230\u8d27\u901a\u77e5",content:'<label><input type="text" id="noticeEmail" class="input tip" value = "\u7535\u5b50\u90ae\u4ef6\uff1a" onfocus = "clearVal(this,\'\u7535\u5b50\u90ae\u4ef6\uff1a\')"/><span id="noticeEmailTip"></span></label><label><input type="text" id="noticePhone" class="input tip" value = "\u624b\u673a\u53f7\u7801\uff1a" onfocus = "clearVal(this,\'\u624b\u673a\u53f7\u7801\uff1a\')"/><span id="noticePhoneTip"></span></label>',
pageX:f.left-6,pageY:f.top-3,button:{"\u786e\u5b9a":function(){var g=$("#noticeEmail").val(),o=$("#noticePhone").val();if((g=="\u7535\u5b50\u90ae\u4ef6\uff1a"||g.length<1)&&(o=="\u624b\u673a\u53f7\u7801\uff1a"||o.length<1)){if(g=="\u7535\u5b50\u90ae\u4ef6\uff1a"||g.length<1){$("#noticeEmailTip").html('<small class="error">\u3000\u90ae\u4ef6\u4e0d\u80fd\u4e3a\u7a7a</small>');return false}if(o=="\u624b\u673a\u53f7\u7801\uff1a"||o.length<1){$("#noticePhoneTip").html('<small class="error">\u3000\u624b\u673a\u4e0d\u80fd\u4e3a\u7a7a</small>');
return false}}if(!(g=="\u7535\u5b50\u90ae\u4ef6\uff1a"||g.length<1))if(!isEmail(g)){$("#noticeEmailTip").html('<small class="error">\u3000\u90ae\u4ef6\u683c\u5f0f\u4e0d\u6b63\u786e</small>');return false}if(!(o=="\u624b\u673a\u53f7\u7801\uff1a"||o.length<1))if(!isPhone(o)){$("#noticePhoneTip").html('<small class="error">\u3000\u624b\u673a\u683c\u5f0f\u4e0d\u6b63\u786e</small>');return false}var n="";if(g!="\u7535\u5b50\u90ae\u4ef6\uff1a"&&g.length)n="\u90ae\u4ef6";if(o!="\u624b\u673a\u53f7\u7801\uff1a"&&
o.length)n="\u77ed\u4fe1";if(g!="\u7535\u5b50\u90ae\u4ef6\uff1a"&&g.length&&o!="\u624b\u673a\u53f7\u7801\uff1a"&&o.length)n="\u90ae\u4ef6\u548c\u77ed\u4fe1";g=g.replace("\u7535\u5b50\u90ae\u4ef6\uff1a","");o=o.replace("\u624b\u673a\u53f7\u7801\uff1a","");$.ajax({type:"POST",url:url.arrNotice+"&skuId="+m+"&email="+g+"&phone="+o+"&random="+url.nowDate+"&jsoncallback=?",dataType:"json",data:l,timeout:6E4,success:function(){$.closepop();$.xiupop({title:"\u5230\u8d27\u901a\u77e5",content:"\u8c22\u8c22\u60a8\u7684\u5173\u6ce8\uff0c\u5230\u8d27\u4f1a\u4ee5"+
n+"\u7684\u65b9\u5f0f\u901a\u77e5\u5230\u60a8",pageX:f.left-6,pageY:f.top-3,button:{"\u5173\u95ed":function(){$.closepop()}}})},error:function(){$.closepop();xiuTips("\u51fa\u9519",f.left,f.top-43,2)}})},"\u53d6\u6d88":function(){$.closepop()}}});break;default:xclkFB(2);$.ajax({type:"POST",url:url.addbag,dataType:"json",data:l,timeout:6E4,async:false,success:function(g){if(g&&g.length>0){g=g[0];if(g.successful!=null){$._xiu_login.showCardNum();jumpToShoppingBag(g.orderId)}else xiuTips(g.failure,f.left,
f.top-43,2)}},error:function(){$.xiupop({content:"\u653e\u5165\u8d2d\u7269\u888b\u5f02\u5e38\uff0c\u8bf7\u68c0\u67e5\u7f51\u7edc",width:"280px",pageX:f.left-6,pageY:f.top-3,button:{"\u5173\u95ed":function(){$.closepop()}}})}});break}return false}}function addSaleoutPic(){}
function selectGoods(b,a,c,d){var e=[];$goodsInfo.data("sid",a).data("cid",b);if(d=="c"){$("#sizesArea a").data("stock",false).addClass("noStock").attr("title","\u6ca1\u6709\u5e93\u5b58");$.each(c,function(h,m){m.stock==1&&m.colorId==b&&e.push(m.sizeId)})}if(d=="s"){$("#colorsArea a").data("stock",false).addClass("noStock").attr("title","\u6ca1\u6709\u5e93\u5b58");$.each(c,function(h,m){m.stock==1&&m.sizeId==a&&e.push(m.colorId)})}for(c=0;c<e.length;c++)$("#"+e[c]).data("stock",true).removeClass("noStock").removeAttr("title");
$goodsInfo.data("catentryId",-1).data("part_number",-1);if(b==-1||a==-1)return false;if(!$goodsInfo.data("preSale")&&!$goodsInfo.data("onSale"))if($("#"+a).data("stock")&&$("#"+b).data("stock")){$goodsInfo.data("stock",true);$goodsInfo.data("kill")?$("#user_buy_btn").removeClass().addClass("user_buy4").attr("title","\u7acb\u5373\u79d2\u6740").unbind("click").bind("click",function(){addShopingBag(this,1);return false}):$("#user_buy_btn").removeClass().addClass("user_buy1").attr("title","\u653e\u5165\u8d2d\u7269\u888b").unbind("click").bind("click",
function(){addShopingBag(this);return false})}else{$goodsInfo.data("stock",false);$("#user_buy_btn").removeClass().addClass("user_buy2").attr("title","\u5230\u8d27\u901a\u77e5").unbind("click").bind("click",function(){addShopingBag(this,20);return false})}$goodsInfo.data("stock")?$("#noStock").remove():addSaleoutPic();c=$("#"+b).text();d=$("#"+a).text();var f=jsonGet(skuInfo);if(f=="")return false;for(f=f.length-1;f>=0;){if(skuInfo[f].colorId==c&&skuInfo[f].sizeId==d){$goodsInfo.data("catentryId",
skuInfo[f].skuId).data("part_number",skuInfo[f].skuNum);skuInfo[f].pic_url!=$goodsInfo.data("picUrl")&&skuInfo[f].pics!=null&&skuInfo[f].pics.length>0&&changeZoom(skuInfo[f]);break}f--}}function picError(b){b.src=$("#errImg50").val()}function minpicLoad(b){parseInt(b.width)>50&&picError(b)}
function changeZoom(b){var a=b.pic_url,c=b.pics,d="";if(typeof b.img_version!="undefined"&&b.img_version!=null&&b.img_version!="null")d="?"+b.img_version;b=$goodsInfo;var e=$("#imgPicDiv"),f=$("#smallPic");b.data("selectRun")&&clearTimeout(b.data("selectRun"));b.data("picUrl",a).data("selectRun",setTimeout(function(){e.find("#bigPic").attr("src",a+"g1_600_600.jpg"+d);e.find("#imgPicMask").attr("src",a+"g1_300_300.jpg"+d);$("img:first",e)[0].src=a+"g1_300_300.jpg"+d;f.empty();$.each(c,function(h,m){h=
$("<dd>");var l=$("<a>"),g=$("<img>");l.attr("href","javascript:;");g.attr("src",a+m+"_50_50.jpg"+d);g.attr("onerror","picError(this);");g.attr("onload","minpicLoad(this);");g.attr("alt",$("#goodsName").val());l.append(g);h.append(l);f.append(h)});$("dd",f).removeClass("dc").eq(0).addClass("dc")},10))}
function appInstallment(b,a){var c=$(b).offset();$.ajax({type:"POST",url:url.addbag,dataType:"json",data:a,timeout:6E4,success:function(d){if(d&&d.length>0){d=d[0];d.successful!=null?jumpToShoppingBag(d.orderId,6):xiuTips(d.failure,c.left,c.top-43,2)}},error:function(){$.xiupop({content:"\u653e\u5165\u8d2d\u7269\u888b\u5f02\u5e38\uff0c\u8bf7\u68c0\u67e5\u7f51\u7edc",width:"280px",pageX:c.left-6,pageY:c.top-3,button:{"\u5173\u95ed":function(){$.closepop()}}})}})}
function sendUserBuyBtnClickData(b){var a="000000"+$("#goodsId").val();a=a.substring(a.length-7);var c=$("#inputQuantity").val();XIU.Window.ctraceClick("dtype=additem|itemid="+a+"|addcart="+b+"|itemnum="+c,"xdpv")}
function addInfo(b){var a=[];b=jsonData(b);a.stock=jsonGet(b.stock);a.nowTime=jsonGet(b.nowTime);a.preferential=jsonGet(b.preferential);a.installmentInfo=jsonGet(b.installmentInfo);a.sizes=jsonGet(b.sizes);a.colors=jsonGet(b.colors);a.sizeColorStock=jsonGet(b.sizeColorStock);a.combinationInfo=jsonGet(b.combinationInfo);a.goods=jsonGet(b.goods);a.saleType=jsonGet(b.saleType);a.activity=jsonGet(b.activity);a.limitGoods=jsonGet(b.limitGoods);a.colorsName=jsonGet(b.colorsName);a.sizesName=jsonGet(b.sizesName);
a.preSaleGoods=jsonGet(b.preSaleGoods);a.goods.globalFlag=jsonGet(a.goods.globalFlag);a.goods.spaceFlag=jsonGet(a.goods.spaceFlag);a.onSale=jsonGet(b.onSale);a.offSaleShow=jsonGet(b.offSaleShow);a.onSaleType=jsonGet(b.onSaleType);a.saleType!="2"&&$("#sellType").val(a.saleType);a.goods.invType=jsonGet(a.goods.invType);var c={"00":'<p class="col1 layer12">\u914d\u9001\u4fe1\u606f\uff1a\u9884\u8ba1<font style="font-weight:bold;color:#d11700">1\u5929\u5185</font>\u4ece\u56fd\u5185\u4ed3\u5e93\u53d1\u8d27\uff0c<font style="font-weight:bold;color:#d11700">2-5\u5929</font>\u9001\u8fbe</p>',
"01":'<p class="col1 layer12">\u914d\u9001\u4fe1\u606f\uff1a\u9884\u8ba1<font style="font-weight:bold;color:#d11700">3-5\u5929</font>\u4ece\u56fd\u5185\u4ed3\u5e93\u53d1\u8d27\uff0c<font style="font-weight:bold;color:#d11700">5-8\u5929</font>\u9001\u8fbe</p>',"40":'<p class="col1 layer12">\u914d\u9001\u4fe1\u606f\uff1a\u9884\u8ba1<font style="font-weight:bold;color:#d11700">5\u5929</font>\u4ece<font style="font-weight:bold;color:#d11700">\u7f8e\u56fd\u4ed3\u5e93</font>\u53d1\u8d27\uff0c<font style="font-weight:bold;color:#d11700">12-18\u5929</font>\u9001\u8fbe</p>',
"41":'<p class="col1 layer12">\u914d\u9001\u4fe1\u606f\uff1a\u9884\u8ba1<font style="font-weight:bold;color:#d11700">5\u5929</font>\u4ece<font style="font-weight:bold;color:#d11700">\u7f8e\u56fd\u4ed3\u5e93</font>\u53d1\u8d27\uff0c<font style="font-weight:bold;color:#d11700">12-18\u5929</font>\u9001\u8fbe</p>',"30":'<p class="col1 layer12">\u914d\u9001\u4fe1\u606f\uff1a\u9884\u8ba1<font style="font-weight:bold;color:#d11700">3\u5929</font>\u4ece<font style="font-weight:bold;color:#d11700">\u7f8e\u56fd\u4ed3\u5e93</font>\u53d1\u8d27\uff0c<font style="font-weight:bold;color:#d11700">12-15\u5929</font>\u9001\u8fbe</p>',
"31":'<p class="col1 layer12">\u914d\u9001\u4fe1\u606f\uff1a\u9884\u8ba1<font style="font-weight:bold;color:#d11700">3\u5929</font>\u4ece<font style="font-weight:bold;color:#d11700">\u7f8e\u56fd\u4ed3\u5e93</font>\u53d1\u8d27\uff0c<font style="font-weight:bold;color:#d11700">12-15\u5929</font>\u9001\u8fbe</p>',"10":'<p class="col1 layer12">\u914d\u9001\u4fe1\u606f\uff1a\u9884\u8ba1<font style="font-weight:bold;color:#d11700">1\u5929\u5185</font>\u4ece<font style="font-weight:bold;color:#d11700">\u9999\u6e2f\u4ed3\u5e93</font>\u53d1\u8d27\uff0c<font style="font-weight:bold;color:#d11700">6-9\u5929</font>\u9001\u8fbe</p>',
"11":'<p class="col1 layer12">\u914d\u9001\u4fe1\u606f\uff1a\u9884\u8ba1<font style="font-weight:bold;color:#d11700">2\u5929</font>\u4ece<font style="font-weight:bold;color:#d11700">\u9999\u6e2f\u4ed3\u5e93</font>\u53d1\u8d27\uff0c<font style="font-weight:bold;color:#d11700">8-11\u5929</font>\u9001\u8fbe</p>',"50":'<p class="col1 layer12">\u914d\u9001\u4fe1\u606f\uff1a\u9884\u8ba1<font style="font-weight:bold;color:#d11700">1\u5929\u5185</font>\u4ece\u56fd\u5185\u4ed3\u5e93\u53d1\u8d27\uff0c<font style="font-weight:bold;color:#d11700">2-5\u5929</font>\u9001\u8fbe</p>',
"51":'<p class="col1 layer12">\u914d\u9001\u4fe1\u606f\uff1a\u9884\u8ba1<font style="font-weight:bold;color:#d11700">5-7\u5929</font>\u4ece\u56fd\u5185\u4ed3\u5e93\u53d1\u8d27\uff0c<font style="font-weight:bold;color:#d11700">6-10\u5929</font>\u9001\u8fbe</p>'},d="";if(a.stock!=0&&a.onSale!=0&&a.goods.spaceFlag!=""&&a.goods.spaceFlag!="null"&&a.goods.spaceFlag!=null)d=c[a.goods.spaceFlag+a.goods.invType];if(typeof d=="undefined"||!d)d="";$goodsInfo.data("colorsName",a.colorsName).data("sizesName",
a.sizesName).data("goodInfo",a.goods);if(a.goods==""||jsonGet(b.goods.goodsId)==""){alert("\u6b64\u5546\u54c1\u53ef\u80fd\u5df2\u88ab\u5220\u9664");return false}var e=[],f=0;c='<a href="#" class="user_buy1" id="user_buy_btn" title="\u653e\u5165\u8d2d\u7269\u888b"></a>';a.saleType=a.saleType.split(",");a.goods.mPrice=jsonGet(a.goods.MPrice);a.goods.xPrice=jsonGet(a.goods.XPrice);a.goods.sPrice=jsonGet(a.goods.SPrice);a.goods.pPrice=jsonGet(a.goods.PPrice);a.goods.pScore=jsonGet(a.goods.PScore);a.goods.xScore=
a.goods.pScore;a.endTime=jsonGet(b.endTime);a.priceType=jsonGet(b.priceType);b=a.goods.mPrice==""?"":"\u3000<span>\u5e02 \u573a \u4ef7\uff1a\uffe5"+a.goods.mPrice+"</span>";var h=xp=fq=jf="",m="";m=a.preferential.detail==""||a.preferential==""?"":'<p class="col1 xs"><span class="xs_ico">\u9650\u65f6\u62a2\u8d2d</span><span class="style32">'+a.goods.sPrice+"</span></p>";var l=true;for(i=0;i<a.saleType.length;i++)switch(a.saleType[i]){case "-1":$goodsInfo.data("mp")?(amp=""):(amp=b);xp=a.goods.pPrice==
""?"":'<p class="col1">\u4fc3 \u9500 \u4ef7\uff1a<span class="style3">'+a.goods.pPrice+"</span>"+amp+"</p>";$goodsInfo.data("mp",true);break;case "1":$goodsInfo.data("mp")?(amp=""):(amp=b);xp=a.goods.pPrice==""?"":'<p class="col1">\u79d2 \u6740 \u4ef7\uff1a<span class="style3">'+a.goods.pPrice+"</span>"+amp+"</p>";c='<a  href="#" class="user_buy4" id="user_buy_btn" title="\u7acb\u5373\u79d2\u6740"></a>';$goodsInfo.data("kill",true).data("mp",true);break;case "3":h=a.goods.xPrice==""?"":'<p class="col1">\u8d70 \u79c0 \u4ef7\uff1a<span class="style3">'+
a.goods.xPrice+"</span>"+b+"</p>";c='<a  href="#" class="user_buy5" id="user_buy_btn" title="\u6211\u8981\u9884\u8ba2"></a>';$goodsInfo.data("preSale",true).data("mp",true);break;case "6":fq=1;break;case "2":$goodsInfo.data("mp")?(amp=""):(amp=b);m="";xp=parseFloat(a.goods.sPrice)<parseFloat(a.goods.xPrice)?a.goods.sPrice==""?"":'<p class="col1 xs"><span class="xs_ico">\u9650\u65f6\u7279\u5356</span><span class="style32">'+a.goods.sPrice+'</span></p><p class="col1">\u8d70 \u79c0 \u4ef7\uff1a<span>'+
a.goods.xPrice+"</span>"+amp+"</p>":a.goods.xPrice==""?"":'<p class="col1 xs"><span class="xs_ico">\u9650\u65f6\u7279\u5356</span><span class="style32">'+a.goods.xPrice+'</span></p><p class="col1 sec_time">'+amp+"</p>";$goodsInfo.data("active",true).data("mp",true);l=false;break;case "4":$goodsInfo.data("mp")?(amp=""):(amp=b);xp=a.goods.xPrice==""?"":'<p class="col1">\u6d3b \u52a8 \u4ef7\uff1a<span class="style3">'+a.goods.xPrice+"</span>"+amp+"</p>";$goodsInfo.data("active",true).data("mp",true);
l=false;break;default:if(a.priceType=="1"){h='<p class="col1 xs"><span class="xs_ico">\u9650\u65f6\u7279\u5356</span><span class="style32">'+a.goods.sPrice+"</span></p>";var g='<p class="col1 sec_time" id="onlyTimeSprice">\u5269\u4f59<span style="color:#CF1700; font-weight:bold" class="h" id="onlyDaySprice">00</span>\u5929<span style="color:#CF1700; font-weight:bold" class="m" id="onlyHourSprice">00</span>\u5c0f\u65f6<span style="color:#CF1700; font-weight:bold" class="s" id="onlyMinuteSprice">00</span>\u5206<span style="color:#CF1700; font-weight:bold" class="hs" id="onlySecondSprice">00</span>\u79d2</p>';
countSpriceOne(a.endTime,a.nowTime)||(g="");h+=g+(a.goods.xPrice==""?"":'<p class="col1">\u8d70 \u79c0 \u4ef7\uff1a<span>'+a.goods.xPrice+"</span>"+b+"</p>")}else if(a.priceType=="3"){h='<p class="col1 xs"><span class="xs_ico">\u9650\u65f6\u56e2\u8d2d</span><span class="style32">'+a.goods.sPrice+"</span></p>";g='<p class="col1 sec_time" id="onlyTimeSprice">\u5269\u4f59<span style="color:#CF1700; font-weight:bold" class="h" id="onlyDaySprice">00</span>\u5929<span style="color:#CF1700; font-weight:bold" class="m" id="onlyHourSprice">00</span>\u5c0f\u65f6<span style="color:#CF1700; font-weight:bold" class="s" id="onlyMinuteSprice">00</span>\u5206<span style="color:#CF1700; font-weight:bold" class="hs" id="onlySecondSprice">00</span>\u79d2</p>';
countSpriceOne(a.endTime,a.nowTime)||(g="");h+=g+(a.goods.xPrice==""?"":'<p class="col1">\u8d70 \u79c0 \u4ef7\uff1a<span>'+a.goods.xPrice+"</span>"+b+"</p>")}else if(a.preferential!=""&&a.preferential.detail!=""){g='<p class="col1 sec_time" id="onlyTimeSprice">\u5269\u4f59<span style="color:#CF1700; font-weight:bold" class="h" id="onlyDaySprice">00</span>\u5929<span style="color:#CF1700; font-weight:bold" class="m" id="onlyHourSprice">00</span>\u5c0f\u65f6<span style="color:#CF1700; font-weight:bold" class="s" id="onlyMinuteSprice">00</span>\u5206<span style="color:#CF1700; font-weight:bold" class="hs" id="onlySecondSprice">00</span>\u79d2</p>';
countSpriceOne(a.endTime,a.nowTime)||(g="");h+=g+(a.goods.xPrice==""?"":'<p class="col1">\u8d70 \u79c0 \u4ef7\uff1a<span>'+a.goods.xPrice+"</span>"+b+"</p>")}else h=a.goods.xPrice==""?"":'<p class="col1">\u8d70 \u79c0 \u4ef7\uff1a<span class="style3">'+a.goods.xPrice+"</span>"+b+"</p>";$goodsInfo.data("mp",true);break}e[f++]='<div id="prd_price_div" class="xxjx" style="padding:5px 0px 0px 2px;">';e[f++]=m+h+xp+jf+d;if(a.activity!=""&&a.activity.left_count>=0&&a.saleType==1)if(l)e[f++]='<p class="col1">\u9500\u552e\u60c5\u51b5\uff1a\u552e\u51fa<span class="layer10">'+
a.activity.sales_count+'</span>\u4ef6\uff1b\u8fd8\u5269<span class="layer10">'+a.activity.left_count+"</span>\u4ef6 </p>";a.activity.end_dt=jsonGet(a.activity.end_dt);if(a.activity.end_dt!=""&&($goodsInfo.data("kill")||$goodsInfo.data("active")))e[f++]='<p class="col1 layer11" id="onlyTime">\u5269\u4f59\u65f6\u95f4\uff1a<span id="onlyDay">00</span>\u5929<span id="onlyHour">00</span>\u65f6<span id="onlyMinute">00</span>\u5206<span id="onlySecond">00</span>\u79d2 </p>';e[f++]="</div>";e[f++]='<div id="prd_attr_div" class="cm">';
e[f++]='<div class="modleDiv">';if(a.colors!=""){e[f++]='<div class="cm_hz" id="colorsArea"><div class="xsxm">'+a.colorsName+'\uff1a</div><div class="cmxs noLimit"><ul>';$.each(a.colors,function(n,k){e[f++]='<li><a href="#" rel="color" id='+k.attrId+">"+k.attrValue+"</a></li>"});e[f++]="</ul></div></div>"}if(a.sizes!=""){e[f++]='<div class="cm_hz" id="sizesArea"><div class="xsxm">'+a.sizesName+'\uff1a</div><div class="cmxs noLimit"><ul>';var o="";$.each(a.sizes,function(n,k){o+=","+k.attrValue;e[f++]=
'<li><a href="#" rel="size" id='+k.attrId+">"+k.attrValue+"</a></li>"});e[f++]="</ul></div></div>"}d="up";if(a.onSale==1)if(a.stock==0){c='<a  href="#" class="user_buy2" id="user_buy_btn" title="\u5230\u8d27\u901a\u77e5"></a>';d="up dis";$goodsInfo.data("onSale",true)}if(a.activity!=""&&a.saleType=="2"&&!a.activity.isActGoods)c='<a class="user_buy8" id="user_buy_btn_onsale" title="\u6d3b\u52a8\u5df2\u7ed3\u675f"></a>';else if(a.onSale==0){c=a.offSaleShow==3?'<a  href="#" class="user_buy2" id="user_buy_btn" title="\u5230\u8d27\u901a\u77e5"></a>':
'<a  class="user_buy7" id="user_buy_btn_onsale" title="\u4e0d\u80fd\u653e\u5165\u8d2d\u7269\u888b"></a>';d="up dis";$goodsInfo.data("onSale",true)}b=jsonGet(a.limitGoods.limitNumber);b=b!=""?b:10;e[f++]='<div class="cm_hz"><div class="xsxm">\u6211\u8981\u4e70\uff1a</div><div class="cmxs"><span class="down dis" id="minusAmount"></span><input type="text" id="inputQuantity" name="inputQuantity" value="1"  limValue="'+b+'"/><span class="'+d+'" id="plusAmount"></span>\u4ef6 </div> </div>';e[f++]='<div class="buy_it rela" >';
e[f++]=c;if(a.installmentInfo!=""&&fq==1&&!$goodsInfo.data("preSale")&&!$goodsInfo.data("kill"))e[f++]='<a id="stageLink" href="#">\u5206\u671f\u4ed8\u6b3e</a> ';e[f++]='<a href="#" class="sc_t" id="addToFavoBtn">\u52a0\u5165\u6536\u85cf</a>';e[f++]="</div>";e[f++]="</div></div>";if($goodsInfo.data("preSale"))e[f++]='<div class="xxjx"><p class="col1 layer11" id="preSaleTime">\u9884\u8ba1\u5230\u8d27\u65f6\u95f4\uff1a<span id="preSaleDay">00</span> \u5929 </p></div>';e=e.join(" ");$("#productLoading").hide();
$goodsInfo.html($goodsInfo.html()+e);if(a.activity!=""&&a.activity.end_dt!=""&&a.nowTime!=""&&($goodsInfo.data("kill")||$goodsInfo.data("active")))countdown(a.activity.end_dt,a.nowTime);$goodsInfo.data("preSale")&&countdownPreSale(a.preSaleGoods.preSaleArrivalTime,a.nowTime);$("#stageLink").click(function(){var n=$(this).offset(),k=[],q=0;colorId=$goodsInfo.data("cid")?$goodsInfo.data("cid"):false;sizeId=$goodsInfo.data("sid")?$goodsInfo.data("sid"):false;if(!colorId||colorId==-1){xiuTips("\u8bf7\u5148\u9009\u62e9 <u>"+
$goodsInfo.data("colorsName")+"</u>",n.left,n.top-43,2);return false}if(!sizeId||sizeId==-1){xiuTips("\u8bf7\u5148\u9009\u62e9 <u>"+$goodsInfo.data("sizesName")+"</u>",n.left,n.top-43,2);return false}if($("#inputQuantity").val()>1){showTipDiv("\u5206\u671f\u4ed8\u6b3e\u53ea\u80fd\u8d2d\u4e70\u4e00\u4ef6\u5546\u54c1",n.left,n.top-44,2);return false}var s=mc=a.installmentInfo.installmentCol;k[q++]='<table width="100%" class="payfor" cellpadding="0" cellspacing="0"><tr><th>\u94f6\u884c</th><th>'+mc.join("\u671f</th><th>")+
"\u671f</th></tr>";$.each(a.installmentInfo.detail,function(r,p){k[q++]='<tr title="'+p.description+'"><td><img src="'+p.bankLogoUrl+'" title="'+p.bankName+'"></td>';for(r=0;r<s.length;r++)if(inArray(s[r],p.times)){var t=getArrayPos(s[r],p.times);k[q++]='<td><span style="color:#f60">'+p.ways[t]+"</span>\u5143 \u00d7 "+p.times[t]+"\u671f</td>"}else k[q++]="<td>-</td>";k[q++]="</tr>"});k[q++]='</table><p><small>\u4fe1\u7528\u5361\u5728\u7ebf\u5206\u671f\uff0c\u5b9e\u65f6\u81ea\u52a8\u5ba1\u6838\uff0c\u652f\u4ed8\u66f4\u5feb\u6377\u66f4\u7701\u5fc3\uff01</small></p><a href="javascript:void(0);" class="appInstallment" onclick="addShopingBag(this,6)"><img src="/static/css/default/img/sqfq.gif" width="83" height="25"></a><small><a href="'+
url.installmentHelp+'" target="_blank">\u67e5\u770b\u5206\u671f\u4ed8\u6b3e\u5e2e\u52a9</a></small>';k=k.join(" ");$.xiupop({title:"\u5206\u671f\u4ed8\u6b3e",content:k,width:"500px",pageX:n.left-202,pageY:n.top-112});return false});$("#addToFavoBtn").click(function(){checkLogin(this,addToFavo);return false});$("#t_u").click(function(){var n=$(this).offset(),k=[],q=0;k[q++]="<ul>";$.each(a.preferential.detail,function(s,r){k[q++]="<li>"+r.activityName+"</li>"});k[q++]="</ul>";k[q++]="<p>\u5171\u8282\u7701\uff1a<em>"+
a.preferential.discountAmount+"</em>\u5143</p>";k=k.join(" ");$.xiupop({title:"\u4eab\u53d7\u7684\u4f18\u60e0\u6d3b\u52a8",content:k,width:"300px",pageX:n.left-232,pageY:n.top+22});return false});$(".cmxs").click(function(n){var k=$(n.target);if(k[0].tagName.toUpperCase()=="A"){k.parent("li").siblings("li").removeClass().end().addClass("selected");if(k[0].rel=="color"){sid=$goodsInfo.data("sid")?$goodsInfo.data("sid"):-1;selectGoods(k[0].id,sid,a.sizeColorStock,"c")}if(k[0].rel=="size"){cid=$goodsInfo.data("cid")?
$goodsInfo.data("cid"):-1;selectGoods(cid,k[0].id,a.sizeColorStock,"s")}n.stopPropagation();return false}});setTimeout(function(){$("a[rel=size]").length>0&&$.each(a.sizes,function(r,p){if(skuInfo[0].sizeId==p.attrValue){$("#"+p.attrId).trigger("click");return false}});$("a[rel=color]").length>0&&$.each(a.colors,function(r,p){if(skuInfo[0].colorId==p.attrValue){$("#"+p.attrId).trigger("click");return false}});a.onSale==1&&$.each(a.sizeColorStock,function(r,p){if(p.stock==1){$("#"+p.colorId).trigger("click");
$("#"+p.sizeId).trigger("click");return false}});var n="000000"+goodsData.goodsId;n=n.substring(n.length-7);var k;switch($("a[class^='user_buy']").attr("class")){case "user_buy1":k="gouwudai";break;case "user_buy2":k="daohuotongzhi";break;case "user_buy3":k="jijiangkaishi";break;case "user_buy4":k="miaosha";break;case "user_buy5":k="woyaoyuding";break;case "user_buy6":k="yixiajia";break;case "user_buy7":k="yishouwan";break;case "user_buy8":k="yijieshu";break;default:k="gouwudai"}var q=$("#colorsArea a").length+
$("#sizesArea a").length,s=$("#colorsArea a:not(.noStock)").length+$("#sizesArea a:not(.noStock)").length;XIU.Window.ctraceClick("dtype=areaload|itemid="+n+"|addcart="+k+"|attr="+q+"|optattr="+s,"xdpv")},300);$("#inputQuantity").blur(function(){checkBuyMumber($(this))}).change(function(){checkBuyMumber($(this))});$("#minusAmount").click(function(){if($(this).hasClass("dis"))return false;input=$("#inputQuantity");val=parseInt(input.val());input.val(val-1);checkBuyMumber(input);return false});$("#plusAmount").click(function(){if($(this).hasClass("dis"))return false;
input=$("#inputQuantity");val=parseInt(input.val());input.val(val+1);checkBuyMumber(input);return false});$("#user_buy_btn").bind("click",function(){switch(this.className){case "user_buy2":addShopingBag(this,20);break;case "user_buy4":addShopingBag(this,1);break;case "user_buy5":addShopingBag(this,3);break;default:addShopingBag(this);break}return false})}function kill(b){checkLogin(b,doKill)}
function doKill(b){var a=$(b).offset(),c=$goodsInfo.data("cid")?$goodsInfo.data("cid"):false,d=$goodsInfo.data("sid")?$goodsInfo.data("sid"):false;if(c)if(d){if(!checkBuyMumber($("#inputQuantity")))return false;a=$goodsInfo.data("catentryId");c=$goodsInfo.data("part_number");d=$("#goodsSn").val();var e=$("#inputQuantity").val();addOrderItems(a,e,url.parm.storeId,url.parm.catalogId,c,d,"1",b)}else xiuTips("\u8bf7\u5148\u9009\u62e9 <u>"+$goodsInfo.data("sizesName")+"</u>",a.left,a.top-43,2);else xiuTips("\u8bf7\u5148\u9009\u62e9 <u>"+
$goodsInfo.data("colorsName")+"</u>",a.left,a.top-43,2)}
function checkBuyMumber(b){if(!b)return false;offset=b.offset();val=b.val();down=$("#minusAmount");up=$("#plusAmount");down.removeClass("dis");up.removeClass("dis");maxVal=parseInt(b.attr("limValue"));if(isNaN(val)){showTipDiv("\u5fc5\u987b\u4e3a\u6570\u5b57",offset.left-20,offset.top-44,2);b.val(1);down.addClass("dis");return false}val==1&&down.addClass("dis");if(val<1){b.val(1);down.addClass("dis");return false}if(maxVal!=0){val==maxVal&&up.addClass("dis");if(val>maxVal){showTipDiv("\u60a8\u6700\u591a\u53ea\u80fd\u8d2d\u4e70 "+
maxVal+" \u4ef6",offset.left-20,offset.top-44,2);b.val(maxVal);up.addClass("dis");return false}}return true}
function addOrderItems(b,a,c,d,e,f,h,m){var l=$(m).offset();$.ajax({type:"POST",url:url.wcsurl+"XOrderItemAddCmd?storeId="+c+"&catalogId="+d+"&sellType="+h+"&part_number="+e+"&method=new&catentryId="+b+"&inputQuantity="+a+"&goods_sn="+f+"&random"+Math.random()+"&jsoncallback=?",dataType:"json",timeout:6E4,success:function(g){var o;if(g&&g.length>0)o=g[0];if(o.successful!=null)if(h=="1")window.location.href=url.wcsurl+"ConfirmOrder?storeId="+c+"&catalogId="+d+"&wcsOrderId="+o.orderId;else{$._xiu_login.showCardNum();
jumpToShoppingBag(o.orderId,storeInfo.storeId,storeInfo.catalogId)}else xiuTips(o.failure,l.left,l.top-43,2)},error:function(g){xiuTips(g,l.left,l.top-43,2)}})}function getParaValue(b,a){b=a.split(b);a=b.length;if(a<2)return"";return b[a-1].split("&")[0].replace(/=/,"")}
function recomFn(){var b=$goodsInfo.data("goodInfo"),a={userId:$.cookie("xiu.login.userId")!=null?$.cookie("xiu.login.userId"):null,objId:b.goodsId,xPrice:b.xPrice,categoryId:$goodsInfo.data("GoodsTypeId"),brandId:$("#brandId").val(),sceneId:"",pageId:"",algorithmInd:""};b=getParaValue("xclk_ind",location.href);if(b!=""){a.sceneId=b.split("_")[0];a.pageId=typeof b.split("_")[1]=="undefined"?"":b.split("_")[1];a.algorithmInd=typeof b.split("_")[2]=="undefined"?"":b.split("_")[2]}try{xclk.onLoad=function(){var d=
new xclk.VO;d.user_id=a.userId;d.obj_id=a.objId;d.obj_type=1;d.x_price=a.xPrice;d.category_id=a.categoryId;d.brand_id=a.brandId;d.scene_id=a.sceneId;d.ref_page_id=a.pageId;d.algorithm_ind=a.algorithmInd;xclk.invoke(d)}}catch(c){}}
function xclkFB(b){try{var a=$goodsInfo.data("goodInfo"),c=new xclk.FB;c.user_id=$.cookie("xiu.login.userId")!=null?$.cookie("xiu.login.userId"):"";c.fb_type=b;var d=new xclk.FbDetail;d.item_id=a.goodsId;d.category_id=$goodsInfo.data("GoodsTypeId");d.brand_id=$("#brandId").val();d.x_price=a.xPrice;c.fb_detail=[d];xclk.invoke(c)}catch(e){}}
function putRecomFn(){var b=$goodsInfo.data("goodInfo");b={userId:$.cookie("xiu.login.userId")!=null?$.cookie("xiu.login.userId"):null,objId:b.goodsId,xPrice:b.xPrice,categoryId:$goodsInfo.data("GoodsTypeId"),brandId:$("#brandId").val(),sceneId:"",pageId:"",algorithmInd:""};var a=getParaValue("xclk_ind",location.href);if(a!=""){b.sceneId=a.split("_")[0];b.pageId=typeof a.split("_")[1]=="undefined"?"":a.split("_")[1];b.algorithmInd=typeof a.split("_")[2]=="undefined"?"":a.split("_")[2]}try{var c=new xres.RecommendVAV("recomCallback");
c.productId=b.objId;c.catId=b.categoryId;c.num=10;xres.invoke(c)}catch(d){}}function recomCallback(b){b=eval(b);var a=document.getElementById("bfd_Box");a.innerHTML="";var c=document.createElement("div");c.className="right_2_t";var d=document.createTextNode("\u4f60\u53ef\u80fd\u5bf9\u4ee5\u4e0b\u5546\u54c1\u611f\u5174\u8da3");c.appendChild(d);a.appendChild(c);c=document.createElement("div");c.className="right_2_con";a.appendChild(c);for(a=0;a<b.length;a++)recomTemplate(b[a],c)}
function recomTemplate(b,a){var c=document.createElement("div");c.className="right_2_pro";html="";html+='<a class="list_img_a" href="'+b.productUrl+'?xres_id=1001"><img title="'+b.name+'" src="'+b.pictureUrl+'" /></a>';html+='<p class="txt"><a href="'+b.productUrl+'?xres_id=1001" title="'+b.name+'">'+b.name+"</a></p>";html+='<p class="jc">'+b.price+"</p>";c.innerHTML=html;a.appendChild(c)}
function bfdStart(){try{var b=new brs.Client("Czouxiu"),a=new brs.PackedRequest,c=$goodsInfo.data("goodInfo"),d=skuInfo[0].pic_url+"g1_100_100.jpg?"+skuInfo[0].img_version;item_id=c.goodsId;var e=$("#goodsName").val(),f=location.href;image_link=d;item_price=c.SPrice||c.XPrice;var h=$goodsInfo.data("type");item_brand=$("#brandName").val();c=[];c.push("all");c.push(item_brand);if(h)for(i=0;i<h.length;i++)c.push(h[i]);item_description=e;user_id=$.cookie("xiu.login.userId")!=null?$.cookie("xiu.login.userId"):
"";session_id=$.cookie("sessionID");if(typeof user_id=="undefined"||user_id=="")user_id=session_id;if($goodsInfo.data("onSale"))a.r=new brs.RemoveItem(item_id);else{var m=self.location.href;if(isFromRecommend(m)){var l=getReqId(m);a.cr=new brs.ClickRecItem(user_id,item_id,session_id,l)}else{a.a=new brs.AddItem(item_id,e,f);a.a.image_link=image_link;a.a.price=item_price;a.a.category=c;a.a.description=item_description;a.v=new brs.VisitItem(user_id,item_id,session_id)}}a.recVAV=new brs.RecByViewAlsoView(new Array(item_id),
user_id,10);b.invoke(a,"bfdCallback")}catch(g){}}function bfd(){var b=0,a=setInterval(function(){b++;if(typeof window.bfd_onload=="function"){window.bfd_onload=bfdStart;window.bfd_onload();clearInterval(a)}if(b>=50)try{clearInterval(a)}catch(c){}},100)}if(window.addEventListener)window.addEventListener("load",getHistory,false);else window.attachEvent&&window.attachEvent("onload",getHistory);function getReqId(b){idx=b.indexOf("req_id=");return b.slice(idx+7)}
function isFromRecommend(b){return b.indexOf("req_id=")==-1?false:true}
function bfdCallback(b){var a=b.recVAV;if(a[0]==0){b=a[1];a=a[2];if(Object.prototype.toString.apply(a)==="[object Array]"){var c=document.getElementById("bfd_Box");onGetGoodsInfo(a,c,b)}}var d="000000"+$("#goodsId").val();d=d.substring(d.length-7);$("#bfd_Box").find("div > a").each(function(e,f){$(f).bind("click",function(){var h=this.href.substring(this.href.lastIndexOf("/")+1,this.href.lastIndexOf("."));XIU.Window.ctraceClick("dtype=recommend|itemid="+d+"|clkid="+h,"xdpv")})});$("#bfd_Box").find("p > a").each(function(e,
f){$(f).bind("click",function(){var h=this.href.substring(this.href.lastIndexOf("/")+1,this.href.lastIndexOf("."));XIU.Window.ctraceClick("dtype=recommend|itemid="+d+"|clkid="+h,"xdpv")})})}
function onGetGoodsInfo(b,a,c){var d=document.createElement("div");d.className="right_2_con";a.innerHTML='<div class="right_2_t">\u4f60\u53ef\u80fd\u5bf9\u4ee5\u4e0b\u5546\u54c1\u611f\u5174\u8da3</div>';a.appendChild(d);var e=b.length>10?10:b.length;for(i=0;i<e;i++)i<7&&template(b[i],d,c);b=document.createElement("a");b.href="http://www.baifendian.com";b.target="_blank";b.className="bfd_img_logo";b.rel="nofollow";a.appendChild(b)}
function template(b,a,c){var d=document.createElement("div");d.className="right_2_pro";html="";html+='<a class="list_img_a" href="'+b[2]+"?req_id="+c+'"><img src="'+b[3]+'" onerror="this.src=\''+$("#errImg100").val()+"'\" /></a>";html+='<p class="txt"><a href="'+b[2]+"?req_id="+c+'">'+b[1]+"</a></p>";html+='<p class="jc">'+b[4]+"</p>";d.innerHTML=html;a.appendChild(d)}
function getQueryString(b){if(location.href.indexOf("?")==-1)return"";for(var a=location.href.substring(location.href.indexOf("?")+1).split("&"),c,d,e=0;e<a.length;e++){c=a[e].indexOf("=");if(c!=-1){d=a[e].substring(0,c);c=a[e].substring(c+1);if(d==b)return unescape(c.replace(/\+/g," "))}}return""}
function clickStream(){var b="000000"+goodsData.goodsId;b=b.substring(b.length-7);$("#positionBox").find("a").each(function(c,d){$(d).bind("click",function(){XIU.Window.ctraceClick("dtype=bread|itemid="+b+"|bread_lev="+(c+1),"xdpv")})});$("#addToFavoBtn").bind("click",function(){XIU.Window.ctraceClick("dtype=collect|itemid="+b,"xdpv")});var a=["wb","renren","sina","kaixin","souhu","mls","email"];$("#shareBox").find("a").each(function(c,d){$(d).bind("click",function(){XIU.Window.ctraceClick("dtype=share|itemid="+
b+"|chunnel="+a[c],"xdpv")})});$("div.right_1_con dl:first-child").find("a").bind("click",function(){XIU.Window.ctraceClick("dtype=brandarea|itemid="+b,"xdpv")});$("#typeBox1").find("a").bind("click",function(){XIU.Window.ctraceClick("dtype=relcat|itemid="+b,"xdpv")});$("#typeBox2").find("a").bind("click",function(){XIU.Window.ctraceClick("dtype=reltag|itemid="+b,"xdpv")});$("#container_ul li").eq(1).bind("click",function(){XIU.Window.ctraceClick("dtype=aftersales|itemid="+b,"xdpv")});$("#container_ul li").eq(2).bind("click",
function(){XIU.Window.ctraceClick("dtype=faq|itemid="+b,"xdpv")});$("#container_ul li").eq(3).bind("click",function(){XIU.Window.ctraceClick("dtype=brandstory|itemid="+b,"xdpv")})}
$(document).ready(function(){$("#container0 .conlist img").load(function(){var b=new Image;b.src=this.src;if(b.width>0&&b.height>0){if(b.width>700){this.width=700;this.height=b.height*700/b.width}else{this.width=b.width;this.height=b.height}this.alt=b.width+"\u00d7"+b.height}}).error(function(){$(this).hide()});window.setTimeout(function(){clickStream()},1E3)});(function(b){b.xiu_jqzoom=function(a){a=b.extend({animate_time:600,small_pic:"smallPic",img_pic_div:"imgPicDiv",img_pic:"imgPic",img_pic_mask:"imgPicMask",img_show:"showimg",big_pic_div:"bigPicDiv",big_pic:"bigPic"},a);b.xiu_jqzoom.init(a)};b.extend(b.xiu_jqzoom,{init:function(a){b.xiu_jqzoom.picListInit(a);b.xiu_jqzoom.picBigInit(a)},picListInit:function(a){var c=document.getElementById(a.big_pic),d=document.getElementById(a.img_pic_mask),e=document.getElementById(a.img_pic);b("#smallPic").delegate("a",
"click",function(f){f.preventDefault();f.stopPropagation();b(this).parent("dd").siblings().removeClass("dc").end().addClass("dc");f=b(this).find("img").attr("src");var h=f.replace("50_50","300_300");f=f.replace("50_50","600_600");c.src=f;d.src=h;b("#"+a.img_pic_mask).fadeIn(a.animate_time,function(){e.src=h;b("#"+a.img_pic_mask).fadeOut(a.animate_time)})})},picBigInit:function(a){var c=0,d=0,e=0,f=document.getElementById(a.img_show),h=document.getElementById(a.big_pic_div),m=document.getElementById(a.big_pic);
b("#"+a.img_pic_div).bind("mouseover",function(){f.style.display="block";h.style.display="block";c=f.offsetHeight/2;d=this.clientWidth-f.clientWidth;e=this.clientHeight-f.clientHeight});b("#"+a.img_pic_div).bind("mousemove",function(l){l=l||window.event;var g=b.xiu_jqzoom.mousePosition(l),o=b.xiu_jqzoom.pageX(this);l=b.xiu_jqzoom.pageY(this);l=g.y-l-c;g=g.x-o-c;l=l<0?0:l>e?e:l;g=g<0?0:g>d?d:g;f.style.top=l+"px";f.style.left=g+"px";g=g>0?g*2:0;m.style.top="-"+(l>0?l*2:0)+"px";m.style.left="-"+g+"px"});
b("#"+a.img_pic_div).bind("mouseout",function(){f.style.display="none";h.style.display="none"})},mousePosition:function(a){return{x:a.clientX+(document.body.scrollLeft||document.documentElement.scrollLeft),y:a.clientY+(document.body.scrollTop||document.documentElement.scrollTop)}},pageX:function(a){return a.offsetParent?a.offsetLeft+b.xiu_jqzoom.pageX(a.offsetParent):a.offsetLeft},pageY:function(a){return a.offsetParent?a.offsetTop+b.xiu_jqzoom.pageY(a.offsetParent):a.offsetTop}})})(jQuery);$.xiu_jqzoom();shareContent_pre="\u6211\u521a\u5728\u8d70\u79c0\u7f51\u4e0a\u5546\u57ce\u53d1\u73b0\u4e2a\u597d\u4e1c\u4e1c:";shareContent_tail=",\u633a\u559c\u6b22\u7684,\u5927\u5bb6\u4e5f\u53ef\u4ee5\u770b\u770b\u3002\u8d70\u79c0\u7f51\u662f\u4e2d\u56fd\u9886\u5148\u7684\u65f6\u5c1a\u5962\u4f88\u54c1\u5728\u7ebf\u8d2d\u7269\u7f51\u7ad9\u3002";shareTitle=encodeURIComponent("\u6211\u521a\u5728\u8d70\u79c0\u7f51\u4e0a\u5546\u57ce\u53d1\u73b0\u4e2a\u597d\u4e1c\u4e1c\uff0c\u5927\u5bb6\u53ef\u4ee5\u770b\u770b");
function share_tx_wb(b,a,c,d,e){c=encodeURI(shareContent_pre+c+"\u5e02\u573a\u4ef7"+d+"\u8d70\u79c0\u4ef7"+e+shareContent_tail+" @XIU-Ketang");d=encodeURI(b);e=encodeURI("appkey");a=encodeURI(a);b=encodeURI(b);window.open("http://v.t.qq.com/share/share.php?title="+c+"&url="+d+"&appkey="+e+"&site="+b+"&pic="+a,"\u8f6c\u64ad\u5230\u817e\u8baf\u5fae\u535a","width=700, height=680, top=0, left=0, toolbar=no, menubar=no, scrollbars=no, location=yes, resizable=no, status=no")}
function share_vivi(b,a,c,d,e){function f(h,m,l,g,o,n,k,q,s){function r(){if(!window.open([p,n].join(""),"mb",["toolbar=0,status=0,resizable=1,width=440,height=430,left=",(h.width-440)/2,",top=",(h.height-430)/2].join("")))t.href=[p,n].join("")}var p="http://v.t.sina.com.cn/share/share.php?appkey=1311731384",t=q||m.location;n=["&url=",l(t),"&title=",l(k||m.title),"&source=",l(g),"&sourceUrl=",l(o),"&content=",s||"gb2312","&pic=",l(n||"")].join("");/Firefox/.test(navigator.userAgent)?setTimeout(r,
0):r()}a=encodeURI(c);b=encodeURI(b);f(screen,document,encodeURIComponent,"","","",shareContent_pre+c+"\u5e02\u573a\u4ef7"+d+"\u8d70\u79c0\u4ef7"+e+shareContent_tail+" @\u8d70\u79c0\u7f51",b,"utf-8")}
function shareSouHu(b,a,c,d,e){c=shareContent_pre+c+"\u5e02\u573a\u4ef7"+d+"\u8d70\u79c0\u4ef7"+e+shareContent_tail;b=encodeURI(b);window.open("http://t.sohu.com/third/post.jsp?url="+encodeURIComponent(b)+"&title="+encodeURIComponent(c)+"&content=utf-8&pic="+encodeURI(a),"_blank","scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes")}
function share_renren(b,a,c,d,e){var f=shareTitle;b=encodeURI(b);c=shareContent_pre+c+"\u5e02\u573a\u4ef7"+d+"\u8d70\u79c0\u4ef7"+e+shareContent_tail;a=encodeURI(a);window.open("http://share.renren.com/share/buttonshare/post/1004?title="+f+"&content="+c+"&pic="+a+"&url="+b+"&sid=452406","_blank","scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes")}
function shareKaiXin(b,a,c,d,e){if(typeof b=="object")b=b.href;var f=shareTitle;c=shareContent_pre+c+"\u5e02\u573a\u4ef7"+d+"\u8d70\u79c0\u4ef7"+e+shareContent_tail;a=encodeURI(a);window.open("http://www.kaixin001.com/repaste/bshare.php?rtitle="+f+"&rpic="+a+"&rurl="+encodeURIComponent(b)+"&rcontent="+encodeURIComponent(c),"_blank","scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes")}
function shareMLS(b,a,c,d,e){if(typeof b=="object")b=b.href;b+=b.indexOf("?")==-1?"?from=12562970&utm_content=12562970&utm_campaign=bd&utm_source=meilishuo&utm_medium=guanggao1":"&from=12562970&utm_content=12562970&utm_campaign=bd&utm_source=meilishuo&utm_medium=guanggao1";b=encodeURIComponent(b);var f=shareTitle;summary=shareContent_pre+c+"\u5e02\u573a\u4ef7"+d+"\u8d70\u79c0\u4ef7"+e+shareContent_tail;a=encodeURIComponent(a);window.open("http://www.meilishuo.com/share/share?url="+b+"&image="+a+"&content="+
encodeURIComponent(summary),"_blank","scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes")};function loadMenu(){$("#headCateDiv").load("/index_category_page_120106.shtml");$(".cType_con li").live({mouseenter:function(){var b=$(this),a=$(".cType_con li").index(b),c=b.offset();subMenu=b.find("div:first");if(a>2){j=a*24;subMenu.find(".tyo_con:first").css({top:"-"+(37+j)+"px"})}if(a==8){j=264;subMenu.find(".tyo_con:first").css({top:"-"+(37+j)+"px"})}if(a==3){j=88;subMenu.find(".tyo_con:first").css({top:"-"+(37+j)+"px"})}subMenu.show()},mouseleave:function(){$(this).find("div:first").hide()}})}
;